name: Deploy para VM

on:
  push:
    branches:
      - main  # Substitua pela branch que deseja monitorar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v3

    - name: Configurar SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "144.22.196.120 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDA7qLYCr1BrueOfRcngUt4hGmAtFNZk3C6fE1a3YxIY6AKNCbUuQfBIpwMc/pJzzIbd88eHgje02SqiVu2v/lYRBJoc3Ongsx5ET2jM4twAYHjcB0uwC59wkwnQxtdARURqmcgXbn8YyUWq1nHiZ/c8RBB+L2JBhnx6SJmGv7lYqYWQIIM/VMWk2gN9dqov370v/Tqh/0GAHu0GtNAnkMzQTM9JInSkuKh7bJUBU19TS9yORQ8OYmMzRkdIyoa104QggVJSRW96GQfUpu86d37Z3acdzMjrc5+YijUYm+jarrQZfh1ELIQ4C2Zb9E8HpAR3aIbPj683fLUlW3Hxnv7lNN4czR1BBqhkT1hJdfcIVOdYyQNPjTfFnTcz2V7l/RxkmG4fHqO5fU2ibXCvzZuluUjqLe8YwXjM/Z0TvAoV8GewREmeoKFW1CmUscw6GUV+HRDYfrHTnQTYqDN9g9lUkDnPNGqLdYX14Sg041+b0CM3GHVK6bGSJdMV2mb84E=" > ~/.ssh/known_hosts

    - name: Deploy na VM
      run: |
        ssh -v -tt ubuntu@144.22.196.120 << 'EOF'
        cd fontes/BotZapLobos/
        git pull origin main
        npm install
        pm2 stop all || true
        pm2 start npm --name "BotZap" -- run start
        EOF